/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javafx.scene.control.ComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author bruno
 */
public class condition extends javax.swing.JFrame {

    /**
     * Creates new form condition
     */
    public condition() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Select Condition");
        MenuFrame mf = new MenuFrame();
        this.setIconImage(mf.getIconImage());
        this.jComboBoxValues.setVisible(false);
        this.jTextFieldValues.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioBin = new javax.swing.JRadioButton();
        jRadioOct = new javax.swing.JRadioButton();
        jRadioDec = new javax.swing.JRadioButton();
        Do = new javax.swing.JButton();
        jComboBoxCondition = new javax.swing.JComboBox<>();
        jComboBoxValues = new javax.swing.JComboBox<>();
        jTextFieldValues = new javax.swing.JTextField();
        jLabelFilter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelWallaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Filter : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Value: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, 20));

        jRadioBin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioBin.setText("HEX");
        jRadioBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBinActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jRadioOct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioOct.setText("OCT");
        jRadioOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioOctActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioOct, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jRadioDec.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioDec.setText("DEC");
        jRadioDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDecActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        Do.setBackground(new java.awt.Color(0, 255, 51));
        Do.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Do.setText("OK");
        Do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoActionPerformed(evt);
            }
        });
        getContentPane().add(Do, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jComboBoxCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==", ">", "<" }));
        jComboBoxCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConditionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 60, -1));

        jComboBoxValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValuesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxValues, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));
        getContentPane().add(jTextFieldValues, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));

        jLabelFilter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jLabelFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Condition: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 120, 90, -1));

        jLabelWallaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/índice_1.jpg"))); // NOI18N
        getContentPane().add(jLabelWallaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConditionActionPerformed
    CreateUdpFilter udp = new CreateUdpFilter();
    CreateIpFilter ip = new CreateIpFilter();
    CreateTcpFilter tcp = new CreateTcpFilter();
    String t = "";
    /*Add the selected conditions to the field of the header that you want to create.*/
    private void DoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoActionPerformed
        if(t == "UDP"){
           switch(jComboBoxCondition.getSelectedIndex()){
                case 0:
                    udp.toret += " == ";
                    break;

                case 1:
                    udp.toret += " > ";
                    break;

                case 2:
                    udp.toret += " < ";
                    break;
            }
            if(jComboBoxValues.getSelectedItem() != null){
                udp.toret += '"';
                udp.toret += jComboBoxValues.getSelectedItem();
                udp.toret += '"';
            }else{
                if(jTextFieldValues.getText().isEmpty()) jTextFieldValues.setText("0");
                udp.toret += '"' + jTextFieldValues.getText() + '"';
                jTextFieldValues.setText("");
            }
            dispose();
            udp.setVisible(true); 
        }else if(t == "IP"){
            switch(jComboBoxCondition.getSelectedIndex()){
                case 0:
                    ip.toret += " == ";
                    break;

                case 1:
                    ip.toret += " > ";
                    break;

                case 2:
                    ip.toret += " < ";
                    break;
            }
            if(jComboBoxValues.getSelectedItem() != null){
                ip.toret += '"';
                ip.toret += jComboBoxValues.getSelectedItem();
                ip.toret += '"';
            }else{
                if(jTextFieldValues.getText().isEmpty()) jTextFieldValues.setText("0");
                ip.toret += '"' + jTextFieldValues.getText() + '"';
                jTextFieldValues.setText("");
            }   
            dispose();
            ip.setVisible(true); 
        }else if(t == "TCP"){
            switch(jComboBoxCondition.getSelectedIndex()){
                case 0:
                    tcp.toret += " == ";
                    break;

                case 1:
                    tcp.toret += " > ";
                    break;

                case 2:
                    tcp.toret += " < ";
                    break;
            }
        
            if(jComboBoxValues.getSelectedItem() != null){
                tcp.toret += '"';
                tcp.toret += jComboBoxValues.getSelectedItem();
                tcp.toret += '"';
            }else{
                if(jTextFieldValues.getText().isEmpty()) jTextFieldValues.setText("0");
                tcp.toret += '"' + jTextFieldValues.getText() + '"';
                jTextFieldValues.setText("");
            }
            dispose();
            tcp.setVisible(true); 
        }
        
    }//GEN-LAST:event_DoActionPerformed
 
    /*Add the field of the selected header in binary.*/
    private void jRadioBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBinActionPerformed
        if(jRadioBin.isSelected()){
            jRadioDec.setEnabled(false);
            jRadioOct.setEnabled(false);
            if(jLabelFilter.getText() == "udp[0:2]" || jLabelFilter.getText() == "udp[2:2]" || jLabelFilter.getText() == "udp[4:2]" 
                    || jLabelFilter.getText() == "udp[6:2]" || jLabelFilter.getText() == "ip[2:2]" || jLabelFilter.getText() == "ip[4:2]"
                    || jLabelFilter.getText() == "(ip[10:2])" || jLabelFilter.getText() == "tcp[0:2]" || jLabelFilter.getText() == "tcp[2:2]"
                    || jLabelFilter.getText() == "tcp[16:2]" || jLabelFilter.getText() == "tcp[18:2]" || jLabelFilter.getText() == "tcp[14:2]")
            {
                String[] values =new String[65536];
                for(int n = 0; n < 65536; n++) {
                    values[n] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[0:1] >> 4)" || jLabelFilter.getText() == "(tcp[12:1] >> 4)"){
                String[] values =new String[16];
                for(int n = 0; n < 16; n++) {
                    values[n] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase()+"0");
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[0:1] << 4) >> 4)"){
                String[] values =new String[16];
                for(int n = 0; n < 16; n++) {
                    values[n] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[1:1] >> 2)"){
                String[] values =new String[64];
                int i = 1;
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                for(int n = 4; n < 253; n+=4) {
                    values[i] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[1:1] << 6) >> 6)"){
                String[] values =new String[4];
                for(int n = 0; n < 4; n++) {
                    values[n] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((tcp[12:1] >> 1) & 0x07)"){
                String[] values =new String[8];
                int i = 1;
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                for(int n = 2; n < 15; n+=2) {
                    values[i] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[6:1] >> 5)"){
                String[] values =new String[8];
                int i = 1;
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                for(int n = 32; n < 226; n+=32) {
                    values[i] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[6:2] << 3) >> 3)"){
                String[] values =new String[8192];
                for(int n = 0; n < 8192; n++) {
                    values[n] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[8:1])" || jLabelFilter.getText() == "(ip[9:1])"){
                String[] values =new String[256];
                for(int n = 0; n < 256; n++) {
                    values[n] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[12:4])" || jLabelFilter.getText() == "(ip[16:4])" 
                    || jLabelFilter.getText() == "tcp[4:4]" || jLabelFilter.getText() == "tcp[8:4]"){
                this.jTextFieldValues.setText("0x");
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[20:16])"){
                this.jTextFieldValues.setText("0x");
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[12:1] & 0x01)"){
                String[] values =new String[2];
                for(int n = 0; n < 2; n++) {
                    values[n] = ("0x"+String.valueOf(Integer.toHexString(n)).toUpperCase()+"0");
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "tcp[20:40]"){
                this.jTextFieldValues.setText("0x");
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x80)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(128)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x40)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(64)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x20)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(32)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x10)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(16)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x08)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(8)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x04)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(4)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x02)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(2)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x01)"){
                String[] values =new String[2];
                values[0] = ("0x"+String.valueOf(Integer.toHexString(0)).toUpperCase());
                values[1] = ("0x"+String.valueOf(Integer.toHexString(1)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }

        }else{
            jRadioDec.setEnabled(true);
            jRadioOct.setEnabled(true);
            this.jTextFieldValues.setText("");
            this.jComboBoxValues.setVisible(false);
            this.jTextFieldValues.setVisible(false);
            this.jComboBoxValues.setModel(new DefaultComboBoxModel());
        }
    }//GEN-LAST:event_jRadioBinActionPerformed

    /*Add the field of the selected header in octal.*/
    private void jRadioOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioOctActionPerformed
        if(jRadioOct.isSelected()){
            jRadioBin.setEnabled(false);
            jRadioDec.setEnabled(false);
            if(jLabelFilter.getText() == "udp[0:2]" || jLabelFilter.getText() == "udp[2:2]" || jLabelFilter.getText() == "udp[4:2]" 
                    || jLabelFilter.getText() == "udp[6:2]" || jLabelFilter.getText() == "ip[2:2]" || jLabelFilter.getText() == "ip[4:2]"
                    || jLabelFilter.getText() == "(ip[10:2])" || jLabelFilter.getText() == "tcp[0:2]" || jLabelFilter.getText() == "tcp[2:2]"
                    || jLabelFilter.getText() == "tcp[16:2]" || jLabelFilter.getText() == "tcp[18:2]" || jLabelFilter.getText() == "tcp[14:2]")
            {
                String[] values =new String[65536];
                for(int n = 0; n < 65536; n++) {
                    values[n] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[0:1] >> 4)" || jLabelFilter.getText() == "(tcp[12:1] >> 4)"){
                String[] values =new String[16];
                int i = 1;
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                for(int n = 16; n < 241; n+=16) {
                    values[i] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[0:1] << 4) >> 4)"){
                String[] values =new String[16];
                for(int n = 0; n < 16; n++) {
                    values[n] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[1:1] >> 2)"){
                String[] values =new String[64];
                int i = 1;
                values[0] = ("0x"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                for(int n = 4; n < 253; n+=4) {
                    values[i] = ("0x"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[1:1] << 6) >> 6)"){
                String[] values =new String[4];
                for(int n = 0; n < 4; n++) {
                    values[n] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((tcp[12:1] >> 1) & 0x07)"){
                String[] values =new String[8];
                int i = 1;
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                for(int n = 2; n < 15; n+=2) {
                    values[i] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[6:1] >> 5)"){
                String[] values =new String[8];
                int i = 1;
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                for(int n = 32; n < 226; n+=32) {
                    values[i] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[6:2] << 3) >> 3)"){
                String[] values =new String[8192];
                for(int n = 0; n < 8192; n++) {
                    values[n] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[8:1])" || jLabelFilter.getText() == "(ip[9:1])"){
                String[] values =new String[256];
                for(int n = 0; n < 256; n++) {
                    values[n] = ("0"+String.valueOf(Integer.toOctalString(n)).toUpperCase());
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[12:4])" || jLabelFilter.getText() == "(ip[16:4])" 
                    || jLabelFilter.getText() == "tcp[4:4]" || jLabelFilter.getText() == "tcp[8:4]"){
                this.jTextFieldValues.setText("0");
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[20:16])"){
                this.jTextFieldValues.setText("0");
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[12:1] & 0x01)"){
                String[] values =new String[2];
                values[0] = ("0"+Integer.toOctalString(0).toUpperCase());
                values[1] = ("0"+Integer.toOctalString(256).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "tcp[20:40]"){
                this.jTextFieldValues.setText("0");
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x80)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(128)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x40)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(64)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x20)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(32)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x10)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(16)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x08)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(8)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x04)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(4)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x02)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(2)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x01)"){
                String[] values =new String[2];
                values[0] = ("0"+String.valueOf(Integer.toOctalString(0)).toUpperCase());
                values[1] = ("0"+String.valueOf(Integer.toOctalString(1)).toUpperCase());
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }

        }else{
            jRadioDec.setEnabled(true);
            jRadioBin.setEnabled(true);
            this.jTextFieldValues.setText("");
            this.jComboBoxValues.setVisible(false);
            this.jTextFieldValues.setVisible(false);
            this.jComboBoxValues.setModel(new DefaultComboBoxModel());
        }
    }//GEN-LAST:event_jRadioOctActionPerformed

    /*Add the field of the selected header in decimal.*/
    private void jRadioDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDecActionPerformed
       if(jRadioDec.isSelected()){
            jRadioBin.setEnabled(false);
            jRadioOct.setEnabled(false);
            if(jLabelFilter.getText() == "udp[0:2]" || jLabelFilter.getText() == "udp[2:2]" || jLabelFilter.getText() == "udp[4:2]" 
                    || jLabelFilter.getText() == "udp[6:2]" || jLabelFilter.getText() == "ip[2:2]" || jLabelFilter.getText() == "ip[4:2]"
                    || jLabelFilter.getText() == "(ip[10:2])" || jLabelFilter.getText() == "tcp[0:2]" || jLabelFilter.getText() == "tcp[2:2]"
                    || jLabelFilter.getText() == "tcp[16:2]" || jLabelFilter.getText() == "tcp[18:2]" || jLabelFilter.getText() == "tcp[14:2]")
            {
                String[] values =new String[65536];
                for(int n = 0; n < 65536; n++) {
                    values[n] = (String.valueOf(n));
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[0:1] >> 4)" || jLabelFilter.getText() == "(tcp[12:1] >> 4)"){
                String[] values =new String[16];
                int i = 1;
                values[0] = (String.valueOf(0));
                for(int n = 16; n < 241; n+=16) {
                    values[i] = (String.valueOf(n));
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[0:1] << 4) >> 4)"){
                String[] values =new String[16];
                for(int n = 0; n < 16; n++) {
                    values[n] = (String.valueOf(n));
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[1:1] >> 2)"){
                String[] values =new String[64];
                int i = 1;
                values[0] = (String.valueOf(0));
                for(int n = 4; n < 253; n+=4) {
                    values[i] = (String.valueOf(n));
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[1:1] << 6) >> 6)"){
                String[] values =new String[4];
                for(int n = 0; n < 4; n++) {
                    values[n] = (String.valueOf(n));
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((tcp[12:1] >> 1) & 0x07)"){
                String[] values =new String[8];
                int i = 1;
                values[0] = (String.valueOf(0));
                for(int n = 2; n < 15; n+=2) {
                    values[i] = (String.valueOf(n));
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[6:1] >> 5)" ){
                String[] values =new String[8];
                int i = 1;
                values[0] = (String.valueOf(0));
                for(int n = 32; n < 226; n+=32) {
                    values[i] = (String.valueOf(n));
                    i += 1;
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "((ip[6:2] << 3) >> 3)"){
                String[] values =new String[8192];
                for(int n = 0; n < 8192; n++) {
                    values[n] = (String.valueOf(n));
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[8:1])" || jLabelFilter.getText() == "(ip[9:1])"){
                String[] values =new String[256];
                for(int n = 0; n < 256; n++) {
                    values[n] = (String.valueOf(n));
                }
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[12:4])" || jLabelFilter.getText() == "(ip[16:4])" 
                    || jLabelFilter.getText() == "tcp[4:4]" || jLabelFilter.getText() == "tcp[8:4]"){
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(ip[20:16])"){
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[12:1] & 0x01)"
                    || jLabelFilter.getText() == "(tcp[13:1] & 0x10)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(256));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "tcp[20:40]"){
                this.jTextFieldValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x80)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(128));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x40)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(64));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x20)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(32));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x10)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(16));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x08)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(8));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x04)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(4));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x02)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(2));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }else if(jLabelFilter.getText() == "(tcp[13:1] & 0x01)"){
                String[] values =new String[2];
                values[0] = (String.valueOf(0));
                values[1] = (String.valueOf(1));
                this.jComboBoxValues.setModel(new DefaultComboBoxModel(values));
                this.jComboBoxValues.setVisible(true);
            }

        }else{
            jRadioOct.setEnabled(true);
            jRadioBin.setEnabled(true);
            this.jTextFieldValues.setText("");
            this.jComboBoxValues.setVisible(false);
            this.jTextFieldValues.setVisible(false);

            this.jComboBoxValues.setModel(new DefaultComboBoxModel());
        }
    }//GEN-LAST:event_jRadioDecActionPerformed

    private void jComboBoxValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValuesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(condition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(condition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(condition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(condition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new condition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Do;
    private javax.swing.JComboBox<String> jComboBoxCondition;
    private javax.swing.JComboBox<String> jComboBoxValues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabelFilter;
    private javax.swing.JLabel jLabelWallaper;
    private javax.swing.JRadioButton jRadioBin;
    private javax.swing.JRadioButton jRadioDec;
    private javax.swing.JRadioButton jRadioOct;
    private javax.swing.JTextField jTextFieldValues;
    // End of variables declaration//GEN-END:variables
}
