/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.sun.awt.AWTUtilities;

/**
 *
 * @author bruno
 */
public class CreateUdpFilter extends javax.swing.JFrame {

    /**
     * Creates new form CreateUdpFilter
     */
    public CreateUdpFilter() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Select Type");
        MenuFrame mf = new MenuFrame();
        this.setIconImage(mf.getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Do = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jButtonChecksum = new javax.swing.JButton();
        jButtonLength = new javax.swing.JButton();
        jButtonSourcePort = new javax.swing.JButton();
        jButtonDestinationPort = new javax.swing.JButton();
        jToggleButtonLength = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        wallaper2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Do.setBackground(new java.awt.Color(0, 255, 51));
        Do.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Do.setText("See Filter");
        Do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoActionPerformed(evt);
            }
        });
        getContentPane().add(Do, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 410, 120, -1));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UDP HEADER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/índice.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 100, 20));

        Back.setBackground(new java.awt.Color(255, 102, 0));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, -1, -1));

        jButtonChecksum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonChecksum.setText("Checksum");
        jButtonChecksum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChecksumActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChecksum, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 230, 460, 40));

        jButtonLength.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLength.setText("Length");
        jButtonLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLengthActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 460, 40));

        jButtonSourcePort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSourcePort.setText("Source Port");
        jButtonSourcePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSourcePortActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSourcePort, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 203, 460, 40));

        jButtonDestinationPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDestinationPort.setText("Destination Port");
        jButtonDestinationPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDestinationPortActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDestinationPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 460, 40));

        jToggleButtonLength.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButtonLength.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButtonLength.setText("Length");
        jToggleButtonLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLengthActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 235, 460, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/udpHeader.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1040, 200));

        wallaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/índice_1.jpg"))); // NOI18N
        wallaper2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        wallaper2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                wallaper2MouseDragged(evt);
            }
        });
        wallaper2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wallaper2MousePressed(evt);
            }
        });
        getContentPane().add(wallaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonLengthActionPerformed

    /*Allows the return to the previous menu.*/
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        SelectTypeFilter obj = new SelectTypeFilter();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /*End the application.*/
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /*Add the filter created.*/
    private void DoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoActionPerformed
        SeeFilter obj = new SeeFilter();
        obj.setVisible(true);
        dispose();
        obj.ret = "UDP";
        SeeFilter.jTextArea1.setText(toret);
    }//GEN-LAST:event_DoActionPerformed
    int x,y;
    /*Allows you to move the menu across the screen by pressing and holding the background image.*/
    private void wallaper2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallaper2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_wallaper2MousePressed

    private void wallaper2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallaper2MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_wallaper2MouseDragged
    String toret = "";
    private void jButtonSourcePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSourcePortActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nudp[2:2]";
        }else{
            toret = "udp[2:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("udp[2:2]");
        c.setVisible(true);
        c.udp = this;
        c.t = "UDP";
        dispose();
    }//GEN-LAST:event_jButtonSourcePortActionPerformed
    
    private void jButtonDestinationPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDestinationPortActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nudp[0:2]";
        }else{
            toret = "udp[0:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("udp[0:2]");
        c.setVisible(true);
        c.udp = this;
        c.t = "UDP";
        dispose();
    }//GEN-LAST:event_jButtonDestinationPortActionPerformed

    private void jButtonLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLengthActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nudp[4:2]";
        }else{
            toret = "udp[4:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("udp[4:2]");
        c.setVisible(true);
        c.udp = this;
        c.t = "UDP";
        dispose();
    }//GEN-LAST:event_jButtonLengthActionPerformed

    private void jButtonChecksumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChecksumActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nudp[6:2]";
        }else{
            toret = "udp[6:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("udp[6:2]");
        c.setVisible(true);
        c.udp = this;
        c.t = "UDP";
        dispose();
    }//GEN-LAST:event_jButtonChecksumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUdpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUdpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUdpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUdpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUdpFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Do;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButtonChecksum;
    private javax.swing.JButton jButtonDestinationPort;
    private javax.swing.JButton jButtonLength;
    private javax.swing.JButton jButtonSourcePort;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButtonLength;
    private javax.swing.JLabel wallaper2;
    // End of variables declaration//GEN-END:variables
}
