/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.io.File;
import javax.swing.JTextArea;

/**
 *
 * @author bruno
 */
public class CreateIpFilter extends javax.swing.JFrame {

    /**
     * Creates new form CreateFilter
     */
    public CreateIpFilter() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Create Filter");
        MenuFrame mf = new MenuFrame();
        this.setIconImage(mf.getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Do = new javax.swing.JButton();
        jButtonVersion = new javax.swing.JButton();
        jButtonIHL = new javax.swing.JButton();
        jButtonDSCP = new javax.swing.JButton();
        jButtonECN = new javax.swing.JButton();
        jButtonTotalLength = new javax.swing.JButton();
        jButtonTdentification = new javax.swing.JButton();
        jButtonFlags = new javax.swing.JButton();
        jButtonFragmentOffset = new javax.swing.JButton();
        jButtonTTL = new javax.swing.JButton();
        jButtonProtocol = new javax.swing.JButton();
        jButtonHeaderChecksum = new javax.swing.JButton();
        jButtonSourceIPAddress = new javax.swing.JButton();
        jButtonDestinationIPAddress = new javax.swing.JButton();
        jButtonOptions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wallaper2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        Back.setBackground(new java.awt.Color(255, 102, 0));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, -1, -1));

        Do.setBackground(new java.awt.Color(0, 255, 51));
        Do.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Do.setText("See Filter");
        Do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoActionPerformed(evt);
            }
        });
        getContentPane().add(Do, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 400, 110, -1));

        jButtonVersion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVersion.setText("Version");
        jButtonVersion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVersionMouseClicked(evt);
            }
        });
        jButtonVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVersionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 115, 110, 30));

        jButtonIHL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIHL.setText("IHL");
        jButtonIHL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIHLActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIHL, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 115, 110, 30));

        jButtonDSCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDSCP.setText("DSCP");
        jButtonDSCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDSCPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDSCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 115, 160, 30));

        jButtonECN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonECN.setText("ECN");
        jButtonECN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonECNActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonECN, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 115, -1, 30));

        jButtonTotalLength.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTotalLength.setText("Total Length");
        jButtonTotalLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalLengthActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTotalLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 115, 420, 30));

        jButtonTdentification.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTdentification.setText("Identification");
        jButtonTdentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTdentificationActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 420, 30));

        jButtonFlags.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFlags.setText("Flags");
        jButtonFlags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlagsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFlags, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 143, 80, 30));

        jButtonFragmentOffset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFragmentOffset.setText("Fragment Offset");
        jButtonFragmentOffset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFragmentOffsetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFragmentOffset, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 340, 30));

        jButtonTTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTTL.setText("TTL");
        jButtonTTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTTLActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 170, 210, 30));

        jButtonProtocol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProtocol.setText("Protocol");
        jButtonProtocol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProtocolActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProtocol, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 170, 210, 30));

        jButtonHeaderChecksum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonHeaderChecksum.setText("Header Checksum");
        jButtonHeaderChecksum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHeaderChecksumActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHeaderChecksum, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 420, 30));

        jButtonSourceIPAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSourceIPAddress.setText("Source IP Address");
        jButtonSourceIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSourceIPAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSourceIPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 840, 30));

        jButtonDestinationIPAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDestinationIPAddress.setText("Destination IP Address");
        jButtonDestinationIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDestinationIPAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDestinationIPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 840, 30));

        jButtonOptions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOptions.setText("Options");
        jButtonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOptionsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 840, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IPv4 Packet");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ip_header.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1030, 320));

        wallaper2.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        wallaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/índice_1.jpg"))); // NOI18N
        wallaper2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        wallaper2.setMaximumSize(new java.awt.Dimension(848, 510));
        wallaper2.setMinimumSize(new java.awt.Dimension(848, 510));
        wallaper2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                wallaper2MouseDragged(evt);
            }
        });
        wallaper2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wallaper2MousePressed(evt);
            }
        });
        getContentPane().add(wallaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Allows the return to the previous menu.*/
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        SelectTypeFilter obj = new SelectTypeFilter();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /*End the application.*/
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /*Add the filter created.*/
    private void DoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoActionPerformed
        // TODO add your handling code here:
        SeeFilter obj = new SeeFilter();
        obj.setVisible(true);
        dispose();
        obj.ret = "IP";
        SeeFilter.jTextArea1.setText(toret);
    }//GEN-LAST:event_DoActionPerformed
    int x, y;
    /*Allows you to move the menu across the screen by pressing and holding the background image.*/
    private void wallaper2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallaper2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_wallaper2MousePressed

    private void wallaper2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallaper2MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_wallaper2MouseDragged
    String toret = "";
    private void jButtonVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVersionActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\n" + "ip[0]";
        }else{
            toret = "ip[0]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[0:1] >> 4)");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonVersionActionPerformed

    private void jButtonIHLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIHLActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[0]";
        }else{
            toret = "ip[0]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("((ip[0:1] << 4) >> 4)");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonIHLActionPerformed

    private void jButtonDSCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSCPActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[1]";
        }else{
            toret = "ip[1]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[1:1] >> 2)");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonDSCPActionPerformed

    private void jButtonECNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonECNActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[1]";
        }else{
            toret = "ip[1]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("((ip[1:1] << 6) >> 6)");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonECNActionPerformed

    private void jButtonTotalLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalLengthActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[2:2]";
        }else{
            toret = "ip[2:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("ip[2:2]");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonTotalLengthActionPerformed

    private void jButtonFlagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlagsActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[6]";
        }else{
            toret = "ip[6]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[6:1] >> 5)");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonFlagsActionPerformed

    private void jButtonTdentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTdentificationActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[4:2]";
        }else{
            toret = "ip[4:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("ip[4:2]");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonTdentificationActionPerformed

    private void jButtonFragmentOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFragmentOffsetActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[6:2]";
        }else{
            toret = "ip[6:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("((ip[6:2] << 3) >> 3)");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonFragmentOffsetActionPerformed

    private void jButtonTTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTTLActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[8:1]";
        }else{
            toret = "ip[8:1]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[8:1])");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonTTLActionPerformed

    private void jButtonProtocolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProtocolActionPerformed
       
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[9:1]";
        }else{
             toret = "ip[9:1]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[9:1])");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonProtocolActionPerformed

    private void jButtonHeaderChecksumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHeaderChecksumActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[10:2]";
        }else{
            toret = "ip[10:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[10:2])");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonHeaderChecksumActionPerformed

    private void jButtonSourceIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSourceIPAddressActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[12:4]";
        }else{
            toret = "ip[12:4]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[12:4])");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonSourceIPAddressActionPerformed

    private void jButtonDestinationIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDestinationIPAddressActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[16:4]";
        }else{
            toret = "ip[16:4]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[16:4])");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonDestinationIPAddressActionPerformed

    private void jButtonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsActionPerformed
        
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\nip[20:16]";
        }else{
            toret = "ip[20:16]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(ip[20:16])");
        c.setVisible(true);
        c.ip = this;
        c.t = "IP";
        dispose();
    }//GEN-LAST:event_jButtonOptionsActionPerformed

    private void jButtonVersionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVersionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVersionMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateIpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateIpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateIpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateIpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateIpFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Do;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButtonDSCP;
    private javax.swing.JButton jButtonDestinationIPAddress;
    private javax.swing.JButton jButtonECN;
    private javax.swing.JButton jButtonFlags;
    private javax.swing.JButton jButtonFragmentOffset;
    private javax.swing.JButton jButtonHeaderChecksum;
    private javax.swing.JButton jButtonIHL;
    private javax.swing.JButton jButtonOptions;
    private javax.swing.JButton jButtonProtocol;
    private javax.swing.JButton jButtonSourceIPAddress;
    private javax.swing.JButton jButtonTTL;
    private javax.swing.JButton jButtonTdentification;
    private javax.swing.JButton jButtonTotalLength;
    private javax.swing.JButton jButtonVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel wallaper2;
    // End of variables declaration//GEN-END:variables
}
