/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

/**
 *
 * @author bruno
 */
public class CreateTcpFilter extends javax.swing.JFrame {

    /** Creates new form CreateTcpFilter */
    public CreateTcpFilter() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Select Type");
        MenuFrame mf = new MenuFrame();
        this.setIconImage(mf.getIconImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        jButtonSourcePort = new javax.swing.JButton();
        jButtonDestinationPort = new javax.swing.JButton();
        jButtonSequenceNumber = new javax.swing.JButton();
        jButtonAcknowledgmentNumber = new javax.swing.JButton();
        jButtonWindowSize = new javax.swing.JButton();
        jButtonUrgentPointer = new javax.swing.JButton();
        jLabelReserved = new javax.swing.JLabel();
        jButtonDataOffset = new javax.swing.JButton();
        jButtonReserved = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonChecksum = new javax.swing.JButton();
        jButtonCWR = new javax.swing.JButton();
        jButtonNS = new javax.swing.JButton();
        jButtonECE = new javax.swing.JButton();
        jButtonURG = new javax.swing.JButton();
        jButtonACK = new javax.swing.JButton();
        jButtonPSH = new javax.swing.JButton();
        jButtonRST = new javax.swing.JButton();
        jButtonSYN = new javax.swing.JButton();
        jButtonFIN = new javax.swing.JButton();
        jButtonOptions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Do = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        wallaper2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        jButtonSourcePort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSourcePort.setText("Source Port");
        jButtonSourcePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSourcePortActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSourcePort, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 113, 450, 30));

        jButtonDestinationPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDestinationPort.setText("Destination Port");
        jButtonDestinationPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDestinationPortActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDestinationPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 113, 450, 30));

        jButtonSequenceNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSequenceNumber.setText("Sequence Number");
        jButtonSequenceNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSequenceNumberActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSequenceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 143, 900, 30));

        jButtonAcknowledgmentNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAcknowledgmentNumber.setText("Acknowledgment Number");
        jButtonAcknowledgmentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcknowledgmentNumberActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcknowledgmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 173, 900, 30));

        jButtonWindowSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonWindowSize.setText("Window Size");
        jButtonWindowSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWindowSizeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonWindowSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 203, 450, 80));

        jButtonUrgentPointer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUrgentPointer.setText("Urgent Pointer");
        jButtonUrgentPointer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUrgentPointerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUrgentPointer, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 283, 450, 30));

        jLabelReserved.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelReserved.setText(" Reserved");
        getContentPane().add(jLabelReserved, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 230, 70, 30));

        jButtonDataOffset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDataOffset.setText("Data Offset");
        jButtonDataOffset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataOffsetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDataOffset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 203, 120, 80));

        jButtonReserved.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReserved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservedActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReserved, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 203, 80, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("  FIN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 240, 30, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("   NS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 30, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText(" ECE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CWR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 40, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("URG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("ACK");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PSH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText(" RST");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 240, 30, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("SYN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TCP PACKET");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jButtonChecksum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonChecksum.setText("Checksum");
        jButtonChecksum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChecksumActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChecksum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 283, 460, 30));

        jButtonCWR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCWRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCWR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 203, 30, 80));

        jButtonNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 203, 30, 80));

        jButtonECE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonECEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonECE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 203, 30, 80));

        jButtonURG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonURGActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonURG, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 203, 30, 80));

        jButtonACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 203, 30, 80));

        jButtonPSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPSHActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPSH, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 203, 20, 80));

        jButtonRST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRSTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRST, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 203, 30, 80));

        jButtonSYN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSYNActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSYN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 203, 30, 80));

        jButtonFIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFINActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 203, 30, 80));

        jButtonOptions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOptions.setText("Options");
        jButtonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOptionsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 313, 910, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cabecera.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Do.setBackground(new java.awt.Color(0, 255, 51));
        Do.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Do.setText("See Filter");
        Do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoActionPerformed(evt);
            }
        });
        getContentPane().add(Do, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 400, 110, -1));

        Back.setBackground(new java.awt.Color(255, 102, 0));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, -1, -1));

        wallaper2.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        wallaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/índice_1.jpg"))); // NOI18N
        wallaper2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        wallaper2.setMaximumSize(new java.awt.Dimension(848, 510));
        wallaper2.setMinimumSize(new java.awt.Dimension(848, 510));
        wallaper2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                wallaper2MouseDragged(evt);
            }
        });
        wallaper2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wallaper2MousePressed(evt);
            }
        });
        getContentPane().add(wallaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*End the application.*/
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /*Add the filter created.*/
    private void DoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoActionPerformed
        SeeFilter obj = new SeeFilter();
        obj.setVisible(true);
        dispose();
        obj.ret = "TCP";
        SeeFilter.jTextArea1.setText(toret);
    }//GEN-LAST:event_DoActionPerformed

    /*Allows the return to the previous menu.*/
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        SelectTypeFilter obj = new SelectTypeFilter();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void wallaper2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallaper2MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_wallaper2MouseDragged
    int x, y;
    /*Allows you to move the menu across the screen by pressing and holding the background image.*/
    private void wallaper2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallaper2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_wallaper2MousePressed
    String toret = "";
    private void jButtonNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[12]";
        }else{
            toret = "tcp[12]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[12:1] & 0x01)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonNSActionPerformed
    
    private void jButtonSourcePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSourcePortActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[0:2]";
        }else{
            toret = "tcp[0:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[0:2]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonSourcePortActionPerformed

    private void jButtonDestinationPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDestinationPortActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[2:2]";
        }else{
            toret = "tcp[2:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[2:2]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonDestinationPortActionPerformed

    private void jButtonSequenceNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSequenceNumberActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[4:4]";
        }else{
            toret = "tcp[4:4]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[4:4]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonSequenceNumberActionPerformed

    private void jButtonAcknowledgmentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcknowledgmentNumberActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[8:4]";
        }else{
            toret = "tcp[8:4]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[8:4]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonAcknowledgmentNumberActionPerformed

    private void jButtonDataOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataOffsetActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[12]";
        }else{
            toret = "tcp[12]";
        } 
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[12:1] >> 4)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonDataOffsetActionPerformed

    private void jButtonReservedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservedActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[12]";
        }else{
            toret = "tcp[12]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("((tcp[12:1] >> 1) & 0x07)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonReservedActionPerformed

    private void jButtonWindowSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWindowSizeActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[14:2]";
        }else{
            toret = "tcp[14:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[14:2]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonWindowSizeActionPerformed

    private void jButtonChecksumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChecksumActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[16:2]";
        }else{
            toret = "tcp[16:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[16:2]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonChecksumActionPerformed

    private void jButtonUrgentPointerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUrgentPointerActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[18:2]";
        }else{
            toret = "tcp[18:2]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[18:2]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonUrgentPointerActionPerformed

    private void jButtonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[20:40]";
        }else{
            toret = "tcp[20:40]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("tcp[20:40]");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonOptionsActionPerformed

    private void jButtonCWRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCWRActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x80)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonCWRActionPerformed

    private void jButtonECEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonECEActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x40)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonECEActionPerformed

    private void jButtonURGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonURGActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x20)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonURGActionPerformed

    private void jButtonACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACKActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x10)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonACKActionPerformed

    private void jButtonPSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPSHActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }       
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x08)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonPSHActionPerformed

    private void jButtonRSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRSTActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }   
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x04)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonRSTActionPerformed

    private void jButtonSYNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSYNActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }  
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x02)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonSYNActionPerformed

    private void jButtonFINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFINActionPerformed
        SeeFilter obj = new SeeFilter();
        String ip = SeeFilter.jTextArea1.getText();
        if(toret != ""){
           toret = toret + "\ntcp[13]";
        }else{
            toret = "tcp[13]";
        }  
        condition c = new condition();
        condition.jLabelFilter.setText("(tcp[13:1] & 0x01)");
        c.setVisible(true);
        c.tcp = this;
        c.t = "TCP";
        dispose();
    }//GEN-LAST:event_jButtonFINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTcpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTcpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTcpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTcpFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTcpFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Do;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButtonACK;
    private javax.swing.JButton jButtonAcknowledgmentNumber;
    private javax.swing.JButton jButtonCWR;
    private javax.swing.JButton jButtonChecksum;
    private javax.swing.JButton jButtonDataOffset;
    private javax.swing.JButton jButtonDestinationPort;
    private javax.swing.JButton jButtonECE;
    private javax.swing.JButton jButtonFIN;
    private javax.swing.JButton jButtonNS;
    private javax.swing.JButton jButtonOptions;
    private javax.swing.JButton jButtonPSH;
    private javax.swing.JButton jButtonRST;
    private javax.swing.JButton jButtonReserved;
    private javax.swing.JButton jButtonSYN;
    private javax.swing.JButton jButtonSequenceNumber;
    private javax.swing.JButton jButtonSourcePort;
    private javax.swing.JButton jButtonURG;
    private javax.swing.JButton jButtonUrgentPointer;
    private javax.swing.JButton jButtonWindowSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelReserved;
    private javax.swing.JLabel wallaper2;
    // End of variables declaration//GEN-END:variables

}
