/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class SeeFilter extends javax.swing.JFrame {

    /**
     * Creates new form SeeFilter
     */
    public SeeFilter() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("See Filter");
        MenuFrame mf = new MenuFrame();
        this.setIconImage(mf.getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        addOther = new javax.swing.JButton();
        export = new javax.swing.JButton();
        jLabelWallaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 480, 360));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("x");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        Back.setBackground(new java.awt.Color(255, 102, 0));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        addOther.setBackground(new java.awt.Color(0, 255, 51));
        addOther.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addOther.setText("Add Another Filter");
        addOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOtherActionPerformed(evt);
            }
        });
        getContentPane().add(addOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        export.setBackground(new java.awt.Color(255, 102, 153));
        export.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        export.setText("Export File");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        getContentPane().add(export, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabelWallaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/índice_1.jpg"))); // NOI18N
        getContentPane().add(jLabelWallaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String ret = "";
    /*Allows the return to the previous menu.*/
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        if(ret == "IP"){
            CreateIpFilter obj = new CreateIpFilter();
            String text = jTextArea1.getText();
            obj.toret = text;
            obj.setVisible(true);
        }else if(ret == "UDP"){
            CreateUdpFilter obj = new CreateUdpFilter();
            String text = jTextArea1.getText();
            obj.toret = text;
            obj.setVisible(true);
        }else if(ret == "TCP"){
            CreateTcpFilter obj = new CreateTcpFilter();
            String text = jTextArea1.getText();
            obj.toret = text;
            obj.setVisible(true);
        }else{
            nDpiFilter obj = new nDpiFilter();
            String text = jTextArea1.getText();
            obj.toret = text;
            obj.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /*End the application.*/
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /*It allows to export the filters created on a file to which the name must be inserted. 
    If the file already exists, you can overwrite or add the new filters to existing ones.*/
    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        try {
            String [] cmd = {"mkdir","-p","/tmp/created"};
            Runtime.getRuntime().exec(cmd);
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(this, "Invalid comand.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser("/tmp/created");
        String path = "";
        try{
            if(jF1.showSaveDialog(null) == jF1.APPROVE_OPTION){
            path = jF1.getSelectedFile().getAbsolutePath();
            //path = "nDPI-dev/bruno/filtrosCreados";
            
                if(new File(path).exists())
                {
                    if(JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(this,"The file exists. Do you want to replace it?","Export File",JOptionPane.YES_NO_OPTION)){
                        File file = new File(path);
                        BufferedWriter bw;

                        bw = new BufferedWriter(new FileWriter(file));
                        jTextArea1.write(bw);
                        bw.close();
                    }else{
                        File file = new File(path);
                        FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                        
                        jTextArea1.setText("\n"+jTextArea1.getText());
                        jTextArea1.write(fw);
                        fw.close();
                    }
                }else{
                    File file = new File(path);
                    BufferedWriter bw;
                    
                    bw = new BufferedWriter(new FileWriter(file));
                    jTextArea1.write(bw);
                    bw.close();
                } 
            }
        }catch (Exception ex){
            ex.printStackTrace();
        }finally{
            SelectTypeFilter obj = new SelectTypeFilter();
            obj.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_exportActionPerformed

    /*It allows adding a new filter to those already created. Send the user to the filter selection menu.*/
    private void addOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOtherActionPerformed
        SelectTypeFilter obj = new SelectTypeFilter();
        obj.text = jTextArea1.getText();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_addOtherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeeFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton addOther;
    private javax.swing.JButton exit;
    private javax.swing.JButton export;
    private javax.swing.JLabel jLabelWallaper;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
