/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;


import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class SelectTypeFilter extends javax.swing.JFrame {

    /**
     * Creates new form SelectType
     */
    public SelectTypeFilter() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Select Type Filter");
        MenuFrame mf = new MenuFrame();
        this.setIconImage(mf.getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Body = new javax.swing.JPanel();
        checkUdp = new javax.swing.JCheckBox();
        checkTcp = new javax.swing.JCheckBox();
        checkIp = new javax.swing.JCheckBox();
        checknDpi = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        ipBack = new javax.swing.JButton();
        ipDo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setAlignmentX(0.0F);
        Header.setAlignmentY(0.0F);
        Header.setMinimumSize(new java.awt.Dimension(860, 38));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 862, 40));

        Body.setAlignmentX(0.0F);
        Body.setAlignmentY(0.0F);
        Body.setMinimumSize(new java.awt.Dimension(860, 362));
        Body.setPreferredSize(new java.awt.Dimension(860, 362));

        checkUdp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkUdp.setText("UDP");
        checkUdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUdpActionPerformed(evt);
            }
        });

        checkTcp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkTcp.setText("TCP");
        checkTcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTcpActionPerformed(evt);
            }
        });

        checkIp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkIp.setText("IP");
        checkIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIpActionPerformed(evt);
            }
        });

        checknDpi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checknDpi.setText("nDpi");
        checknDpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checknDpiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT THE FILTER´S TYPE TO CREATE A FILTER.");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(checkUdp)
                .addGap(92, 92, 92)
                .addComponent(checkTcp)
                .addGap(91, 91, 91)
                .addComponent(checkIp)
                .addGap(91, 91, 91)
                .addComponent(checknDpi)
                .addGap(199, 199, 199))
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(127, 127, 127)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkUdp)
                    .addComponent(checkTcp)
                    .addComponent(checkIp)
                    .addComponent(checknDpi))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        getContentPane().add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 862, 365));

        Footer.setPreferredSize(new java.awt.Dimension(852, 39));

        ipBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        ipBack.setAlignmentY(0.0F);
        ipBack.setLabel("Back");
        ipBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipBackActionPerformed(evt);
            }
        });

        ipDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/do.png"))); // NOI18N
        ipDo.setText("Do");
        ipDo.setToolTipText("");
        ipDo.setAlignmentY(0.0F);
        ipDo.setMaximumSize(new java.awt.Dimension(67, 23));
        ipDo.setMinimumSize(new java.awt.Dimension(67, 23));
        ipDo.setPreferredSize(new java.awt.Dimension(67, 23));
        ipDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipDoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(680, Short.MAX_VALUE)
                .addComponent(ipDo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ipBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ipDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ipBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 860, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Check that the udp button is selected. If selected, it prevents the selection of the rest.*/
    private void checkUdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUdpActionPerformed
        // TODO add your handling code here:
        if(checkUdp.isSelected()){
            checkTcp.setSelected(false);
            checkIp.setSelected(false);
            checknDpi.setSelected(false);
        }
    }//GEN-LAST:event_checkUdpActionPerformed

    /*Check that the ndpi button is selected. If selected, it prevents the selection of the rest.*/
    private void checknDpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checknDpiActionPerformed
        // TODO add your handling code here:
        if(checknDpi.isSelected()){
            checkTcp.setSelected(false);
            checkIp.setSelected(false);
            checkUdp.setSelected(false);
        }
    }//GEN-LAST:event_checknDpiActionPerformed

    /*Check that the tcp button is selected. If selected, it prevents the selection of the rest.*/
    private void checkTcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTcpActionPerformed
        // TODO add your handling code here:
        if(checkTcp.isSelected()){
            checkUdp.setSelected(false);
            checkIp.setSelected(false);
            checknDpi.setSelected(false);
        }
    }//GEN-LAST:event_checkTcpActionPerformed

    /*Check that the ip button is selected. If selected, it prevents the selection of the rest.*/
    private void checkIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIpActionPerformed
        // TODO add your handling code here:
        if(checkIp.isSelected()){
            checkTcp.setSelected(false);
            checkUdp.setSelected(false);
            checknDpi.setSelected(false);
        }
    }//GEN-LAST:event_checkIpActionPerformed

    String text = "";
    /*Initializes the filter creation menu that has been selected.*/
    private void ipDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipDoActionPerformed
        // TODO add your handling code here:
        if(checkTcp.isSelected()){
            CreateTcpFilter obj = new CreateTcpFilter();
            obj.toret = text;
            obj.setVisible(true);
            dispose();
        }else if(checkIp.isSelected()){
            CreateIpFilter obj = new CreateIpFilter();
            obj.toret = text;
            obj.setVisible(true);
            dispose();
        }else if(checkUdp.isSelected()){
            CreateUdpFilter obj = new CreateUdpFilter();
            obj.toret = text;
            obj.setVisible(true);
            dispose();
        }else if(checknDpi.isSelected()){
            nDpiFilter obj = new nDpiFilter();
            obj.toret = text;
            obj.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Select a type.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_ipDoActionPerformed

    /*Allows the return to the previous menu.*/
    private void ipBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipBackActionPerformed
        // TODO add your handling code here:
         MenuFrame obj = new MenuFrame();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ipBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTypeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTypeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTypeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTypeFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTypeFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JCheckBox checkIp;
    private javax.swing.JCheckBox checkTcp;
    private javax.swing.JCheckBox checkUdp;
    private javax.swing.JCheckBox checknDpi;
    private javax.swing.JButton ipBack;
    private javax.swing.JButton ipDo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
